const CACHE = "prato-do-dia-v7";
const SHELL = ["./","./index.html","./manifest.webmanifest","./sw.js","./assets/index-CZ9VoIu1.js","./assets/index-CWVMaK0X.css","./icon-192.png","./icon-512.png","./icon-mask-192.png","./icon-mask-512.png","./favicon.png","./favicon-32.png","./apple-touch-icon.png","./logo-plano-mestre.png"];
const DB = "prato-do-dia-offline";
const DEFAULTS = {profile:{name:"Fausto",configured:0,sex:"M",height:182,weight:120.1,goal:"perder",adjustPct:20,activityFactor:1.2},body:[],entries:[],exercises:[],users:[{id:"principal",name:"Fausto"}],settings:{}};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore("data");r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getData(key){try{const db=await openDB();return await new Promise((resolve,reject)=>{const r=db.transaction("data").objectStore("data").get(key);r.onsuccess=()=>resolve(r.result??DEFAULTS[key]);r.onerror=()=>reject(r.error)})}catch(_){return DEFAULTS[key]}}
async function putData(key,value){try{const db=await openDB();await new Promise((resolve,reject)=>{const r=db.transaction("data","readwrite").objectStore("data").put(value,key);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}catch(_) {}}
function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json; charset=utf-8"}})}
async function api(req,url){const marker="/port/5000";const markerAt=url.pathname.indexOf(marker);const path=markerAt>=0?url.pathname.slice(markerAt+marker.length):url.pathname;const key=path.includes("/profile")?"profile":path.includes("/body")?"body":path.includes("/entries")?"entries":path.includes("/exercises")?"exercises":path.includes("/settings")?"settings":path.includes("/users")?"users":null;if(!key)return json({});let value=await getData(key);if(req.method==="GET")return json(value);let incoming={};try{incoming=await req.json()}catch(_){}if(key==="users"&&path==="/api/users"){const user={id:"principal",name:incoming.name||"Fausto"};value=[user];await putData(key,value);return json(user,201)}if(req.method==="POST"){if(!Array.isArray(value))value=[];const item={...incoming,id:Date.now()};value.push(item);await putData(key,value);return json(item,201)}if(req.method==="PATCH"){if(Array.isArray(value))value=value.map(x=>String(x.id)===path.split("/").pop()?{...x,...incoming}:x);else value={...value,...incoming};await putData(key,value);return json(value)}if(req.method==="DELETE"){if(Array.isArray(value)){value=value.filter(x=>String(x.id)!==path.split("/").pop());await putData(key,value)}return json({ok:true})}return json(value)}
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL).catch(()=>undefined)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{const req=e.request,url=new URL(req.url);if(url.pathname.includes("/port/5000/api/")){e.respondWith(api(req,url));return}if(req.mode==="navigate"){e.respondWith(fetch(req).catch(()=>caches.match("./index.html")));return}e.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(req,res.clone()));return res}).catch(()=>hit)))});
